# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.


# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "vmware-iso" "moiflab-ub01" {

# Boot Commands - here, we're starting a local HTTP server on our bootstrap machine to serve the user-data file containing the cloud-init instructions

  boot_command           = ["<enter><enter><f6><esc><wait> ", "autoinstall ds=nocloud-net;seedfrom=http://{{ .HTTPIP }}:{{ .HTTPPort }}/", "<enter><wait>"]
  boot_wait              = "3s"

# Initial VM Specifications

  disk_size              = 40000
  disk_type_id           = "thin"
  guest_os_type          = "ubuntu-64"
  keep_registered        = true
  skip_export            = true

# Directories for user-data, meta-data and VM output (if required)

  http_directory         = "http"
  output_directory       = "output"

# ISO details

  iso_checksum           = "28ccdb56450e643bad03bb7bcf7507ce3d8d90e8bf09e38f6bd9ac298a98eaad"
  iso_url                = "[Synology_vmware_esxi] Installers/ubuntu-20.04.1-live-server-amd64.iso"

# Remote details eg: how to connect to ESXi

  remote_cache_datastore = var.remote_cache_datastore
  remote_datastore       = var.remote_datastore
  remote_host            = var.remote_host
  remote_password        = var.remote_password
  remote_type            = var.remote_type
  remote_username        = var.remote_username

  shutdown_command       = "shutdown -P now"

# SSH details once the VM has completed cloud-init

  ssh_handshake_attempts = 2000
  ssh_password           = "VMware123!"
  ssh_pty                = true
  ssh_timeout            = "30m"
  ssh_username           = "moiflab"

# Actual VM data

  vmx_data = {
    "ethernet0.addressType"    = "generated"
    "ethernet0.networkName"    = "10.32.0.0/24"
    "ethernet0.present"        = "TRUE"
    "ethernet0.startConnected" = "TRUE"
    "ethernet0.virtualDev"     = "vmxnet3"
    "ethernet0.wakeOnPcktRcv"  = "FALSE"
    memsize                    = "1024"
    numvcpus                   = "1"
  }

# We're connecting over websocket (VM Console)

  vnc_over_websocket     = true
  insecure_connection    = true
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.vmware-iso.moiflab-ub01"]

  provisioner "shell" {
    inline = ["ls /"]
  }

}  